const pages = [
  'https://www.angelsshop.com.ua/аксессуары',
  'https://www.angelsshop.com.ua/бикини',
  'https://www.angelsshop.com.ua/боди',
  'https://www.angelsshop.com.ua/боди-и-пеньюары',
  'https://www.angelsshop.com.ua/брелки',
  'https://www.angelsshop.com.ua/бюстгальтеры',
  'https://www.angelsshop.com.ua/комплекты-белья',
  'https://www.angelsshop.com.ua/косметика-для-лица',
  'https://www.angelsshop.com.ua/косметика-для-тела',
  'https://www.angelsshop.com.ua/косметички',
  'https://www.angelsshop.com.ua/кофты-футболки-майки',
  'https://www.angelsshop.com.ua/маски-для-лица',
  'https://www.angelsshop.com.ua/ночные-сорочки',
  'https://www.angelsshop.com.ua/о-компании',
  'https://www.angelsshop.com.ua/обувь',
  'https://www.angelsshop.com.ua/парфюмерия',
  'https://www.angelsshop.com.ua/пижамы',
  'https://www.angelsshop.com.ua/пляжные-сумки',
  'https://www.angelsshop.com.ua/подарочные-наборы',
  'https://www.angelsshop.com.ua/подарочные-наборы-и-сертификаты',
  'https://www.angelsshop.com.ua/пояса',
  'https://www.angelsshop.com.ua/разное',
  'https://www.angelsshop.com.ua/слитные-купальники',
  'https://www.angelsshop.com.ua/спортивные-костюмы-комбинезоны',
  'https://www.angelsshop.com.ua/спортивные-топы',
  'https://www.angelsshop.com.ua/сумки-и-рюкзаки',
  'https://www.angelsshop.com.ua/тапочки-и-аксессуары',
  'https://www.angelsshop.com.ua/трусики',
  'https://www.angelsshop.com.ua/туники',
  'https://www.angelsshop.com.ua/халаты',
  'https://www.angelsshop.com.ua/шлёпанцы',
]


module.exports = pages
